version: '3.9'

services:

  cribl-leader:
    image: ${CRIBL_IMAGE:-cribl/cribl:latest}
    environment:
      - CRIBL_DIST_MODE=master
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@0.0.0.0:4200
      - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
    ports:
      - 19000:9000
    volumes:
      - "cribl-config:/opt/cribl/config-volume"

  cribl-worker:
    image: ${CRIBL_IMAGE:-cribl/cribl:latest}
    depends_on:
      - cribl-leader
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@cribl-leader:4200
    ports:
      - 9000

  redis:
    image: ${REDIS_IMAGE:-redis:latest}
    ports:
      - 6379:6379

  splunk-so:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changem3N0w!
    ports:
      - 18000:8000
      - 8089
      - 9997
      - 8088
    volumes:
      - "splunk-so-etc:/opt/splunk/etc"
      - "splunk-so-var:/opt/splunk/var"

volumes:
  cribl-config:
  splunk-so-etc:
  splunk-so-var:
